### ISSUE TITLE
work on the wire frame

### ISSUE THREAD

**Issue by jackdee0077** [jackdee0077/Elite-Eats#16]

**Comment by jerielslay** [comment]
<img width="952" alt="Screenshot 2022-12-22 at 7 04 45 PM" src="https://user-images.githubusercontent.com/111207490/209245578-ce1b0568-1916-4d51-9632-ce1dd9fb3225.png">

**Comment by jerielslay** [comment]
Wireframe completed with mapping of the apps functions.
