### ISSUE TITLE
make necessary review on ER diagram

### ISSUE THREAD

**Issue by jackdee0077** [jackdee0077/Elite-Eats#17]

**Comment by jerielslay** [comment]
<img width="653" alt="Screenshot 2022-12-22 at 7 04 05 PM" src="https://user-images.githubusercontent.com/111207490/209245554-9451297e-f558-4dea-ae2e-b7153d91cc86.png">

**Comment by jerielslay** [comment]
ER diagram completed; displaying 1-to-many and many-to-many relationship
